[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python', 'py']
hook_add = '''
 " 補完で次の候補に進むときにtabを使えるという設定にしたつもりですができませんでした。
  let g:jedi#use_tabs_not_buffers = 1 
 " 1個目の候補が入力されるっていう設定を解除
  let g:jedi#popup_select_first = 0
 " quick-runと競合しないように大文字Rに変更. READMEだと<leader>r
  let g:jedi#rename_command = "<leader>R"
 " ポップアップを表示しない
  autocmd FileType python setlocal completeopt-=preview
  let g:python_host_prog = '/full/path/to/neovim2/bin/python'
  let g:python3_host_prog = '/full/path/to/neovim3/bin/python'
'''
